new dockerfile

diff --git a/docker/myserver/dockerfile b/docker/myserver/dockerfile
--- a/docker/myserver/dockerfile
+++ b/docker/myserver/dockerfile
@@ -1,33 +1,32 @@
-FROM ubuntu:22.04
-RUN echo 'APT::Install-Suggests "0";' >> /etc/apt/apt.conf.d/00-docker
-RUN echo 'APT::Install-Recommends "0";' >> /etc/apt/apt.conf.d/00-docker
+# Use an official Ubuntu base image
+FROM ubuntu:24.04
 
-RUN DEBIAN_FRONTEND=noninteractive 
-RUN apt update \
-  && apt upgrade -y \
-  && apt install -y --no-install-recommends \
-    ca-certificates \
-    curl \
-    htop \
-    iotop \
-    rsync \
-    tar \
-    vim \
-    unzip \
-    systemctl \
-    sudo \
-#    systemd \
-#    ufw \
-    openssh-server \
-  && apt clean all \
-  && apt autoremove
+# Set environment variables to avoid interactive prompts during installation
+ENV DEBIAN_FRONTEND=noninteractive
+ENV SSH_USERNAME="ubuntu"
+ENV SSHD_CONFIG_ADDITIONAL=""
 
-# Install dockerize for config files
-RUN curl -sfL $(curl -s https://api.github.com/repos/powerman/dockerize/releases/latest \
-  | grep -i /dockerize-$(uname -s)-$(uname -m)\" | cut -d\" -f4) \
-  | install /dev/stdin /usr/local/bin/dockerize
+# Install OpenSSH server, clean up, create directories, set permissions, and configure SSH
+RUN apt-get update \
+    && apt-get install -y iproute2 iputils-ping openssh-server telnet \
+    && apt-get clean \
+    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
+    && mkdir -p /run/sshd \
+    && chmod 755 /run/sshd \
+    && if ! id -u "$SSH_USERNAME" > /dev/null 2>&1; then useradd -ms /bin/bash "$SSH_USERNAME"; fi \
+    && chown -R "$SSH_USERNAME":"$SSH_USERNAME" /home/"$SSH_USERNAME" \
+    && chmod 755 /home/"$SSH_USERNAME" \
+    && mkdir -p /home/"$SSH_USERNAME"/.ssh \
+    && chown "$SSH_USERNAME":"$SSH_USERNAME" /home/"$SSH_USERNAME"/.ssh \
+    && echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config \
+    && echo "PermitRootLogin no" >> /etc/ssh/sshd_config
 
-RUN sudo systemctl enable ssh
-# RUN sudo systemctl start ssh
+# Copy the script to configure the user's password and authorized keys
+COPY configure-ssh-user.sh /usr/local/bin/
+RUN chmod +x /usr/local/bin/configure-ssh-user.sh
 
-USER root
+# Expose SSH port
+EXPOSE 22
+
+# Start SSH server
+CMD ["/usr/local/bin/configure-ssh-user.sh"]
